services:
  db:
    image: postgres:16-alpine
    container_name: jarra_postgres_prod
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-jarra_website}
      TZ: UTC
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - jarra_prod_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jarra_backend_prod
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - DB_NAME=${DB_NAME:-jarra_website}
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=https://${DOMAIN}
      - SOCKET_PORT=5000
      - TZ=UTC
      - APP_TIMEZONE=Africa/Addis_Ababa
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - jarra_prod_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_URL=https://${DOMAIN}/api
        - NEXT_PUBLIC_BASE=https://${DOMAIN}
        - NEXT_PUBLIC_TIMEZONE=Africa/Addis_Ababa
    container_name: jarra_frontend_prod
    restart: always
    environment:
      - NODE_ENV=production
      - INTERNAL_API_URL=http://backend:4000/api
      - NEXT_PUBLIC_BASE_URL=https://${DOMAIN}/api
      - NEXT_PUBLIC_BASE=https://${DOMAIN}
      - NEXT_PUBLIC_TIMEZONE=Africa/Addis_Ababa
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=https://${DOMAIN}/api/auth
      - NEXTAUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL=https://${DOMAIN}/api/auth
    depends_on:
      - backend
    networks:
      - jarra_prod_network

  nginx:
    image: nginx:stable-alpine
    container_name: jarra_nginx_prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
    command: /bin/sh /etc/nginx/templates/start.sh
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - jarra_prod_network

  certbot:
    image: certbot/certbot
    container_name: jarra_certbot
    environment:
      - CERTBOT_DOMAIN=${DOMAIN}
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh /etc/nginx/templates/certbot-entrypoint.sh
    networks:
      - jarra_prod_network

volumes:
  postgres_data_prod:

networks:
  jarra_prod_network:
    driver: bridge
