services:
  db:
    image: postgres:16-alpine
    container_name: jarra_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-jarra_website}
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jarra_backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - DB_NAME=${DB_NAME:-jarra_website}
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET:-fallback_secret}
      - FRONTEND_URL=http://localhost
      - TZ=UTC
      - APP_TIMEZONE=Africa/Addis_Ababa
    expose:
      - "4000"
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_URL=http://localhost/api
        - NEXT_PUBLIC_BASE=http://localhost
        - NEXT_PUBLIC_TIMEZONE=Africa/Addis_Ababa
    container_name: jarra_frontend
    restart: always
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost/api
      - NEXT_PUBLIC_BASE=http://localhost
      - NEXT_PUBLIC_TIMEZONE=Africa/Addis_Ababa
      - AUTH_SECRET=${AUTH_SECRET:-fallback_nextauth_secret_6yuOtU4X6sQnw2BHlFjGO}
      - AUTH_URL=http://localhost/api/auth
      - NEXTAUTH_SECRET=${AUTH_SECRET:-fallback_nextauth_secret_6yuOtU4X6sQnw2BHlFjGO}
      - NEXTAUTH_URL=http://localhost/api/auth
    expose:
      - "3000"
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: jarra_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
